version: '3'

networks:
  default:
    external: false

services:
  server:
    container_name: $NAME
    hostname: $NAME
    build:
      context: "./context"
      args:
        - USER
        - UID
        - GID
        - PASSWORD
        - RUBYVER
        - RAILSVER
        - POSTGRES_VER
    restart: always
    environment:
      - TZ
      - LANG
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./ssh:/home/$USER/.ssh
      - ./workspace:/home/$USER/workspace
    ports:
      - "${PORT}:22"
    depends_on:
      - db
    networks:
      - default
    tty: true

  db:
    image: postgres:$POSTGRES_VER
    container_name: '${NAME}_postgresql'
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - default
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

